int[] cycles = {
  7, 6, 2, 8, 3, 3, 5, 5, 3, 2, 2, 2, 4, 4, 6, 6,
  2, 5, 2, 8, 4, 4, 6, 6, 2, 4, 2, 7, 4, 4, 7, 7,
  6, 6, 2, 8, 3, 3, 5, 5, 4, 2, 2, 2, 4, 4, 6, 6,
  2, 5, 2, 8, 4, 4, 6, 6, 2, 4, 2, 7, 4, 4, 7, 7,
  6, 6, 2, 8, 3, 3, 5, 5, 3, 2, 2, 2, 3, 4, 6, 6,
  2, 5, 2, 8, 4, 4, 6, 6, 2, 4, 2, 7, 4, 4, 7, 7,
  6, 6, 2, 8, 3, 3, 5, 5, 4, 2, 2, 2, 4, 4, 6, 6,
  2, 5, 2, 8, 4, 4, 6, 6, 2, 4, 2, 7, 4, 4, 7, 7,
  2, 6, 2, 6, 3, 3, 3, 3, 2, 2, 2, 2, 4, 4, 4, 4,
  2, 6, 2, 6, 4, 4, 4, 4, 2, 5, 2, 5, 5, 5, 5, 5,
  2, 6, 2, 6, 3, 3, 3, 3, 2, 2, 2, 2, 4, 4, 4, 4,
  2, 5, 2, 5, 4, 4, 4, 4, 2, 4, 2, 4, 4, 4, 4, 4,
  2, 6, 2, 8, 3, 3, 5, 5, 2, 2, 2, 2, 4, 4, 6, 6,
  2, 5, 2, 8, 4, 4, 6, 6, 2, 4, 2, 7, 4, 4, 7, 7,
  2, 6, 2, 8, 3, 3, 5, 5, 2, 2, 2, 2, 4, 4, 6, 6,
  2, 5, 2, 8, 4, 4, 6, 6, 2, 4, 2, 7, 4, 4, 7, 7
};

Object[][] nesController = {
  {88, false},
  {90, false},
  {32, false},
  {10, false},
  {38, false},
  {40, false},
  {37, false},
  {39, false},
};

// unused, might use for some disassembly stuff
Object[][] disassemblyOpcodeTable = {
    {"BRK","IMPL"}, {"ORA","IND,X"}, {"JAM","IMPL"}, {"SLO","IND,X"},
    {"NOP","ZPG"},  {"ORA","ZPG"},   {"ASL","ZPG"},  {"SLO","ZPG"},
    {"PHP","IMPL"}, {"ORA","IMM"},   {"ASL","ACC"},  {"ANC","IMM"},
    {"NOP","ABS"},  {"ORA","ABS"},   {"ASL","ABS"},  {"SLO","ABS"},
    {"BPL","REL"},  {"ORA","IND,Y"}, {"JAM","IMPL"}, {"SLO","IND,Y"},
    {"NOP","ZPG,X"},{"ORA","ZPG,X"}, {"ASL","ZPG,X"},{"SLO","ZPG,X"},
    {"CLC","IMPL"}, {"ORA","ABS,Y"}, {"NOP","IMPL"}, {"SLO","ABS,Y"},
    {"NOP","ABS,X"},{"ORA","ABS,X"}, {"ASL","ABS,X"},{"SLO","ABS,X"},
    {"JSR","ABS"},  {"AND","IND,X"}, {"JAM","IMPL"}, {"RLA","IND,X"},
    {"BIT","ZPG"},  {"AND","ZPG"},   {"ROL","ZPG"},  {"RLA","ZPG"},
    {"PLP","IMPL"}, {"AND","IMM"},   {"ROL","ACC"},  {"ANC","IMM"},
    {"BIT","ABS"},  {"AND","ABS"},   {"ROL","ABS"},  {"RLA","ABS"},
    {"BMI","REL"},  {"AND","IND,Y"}, {"JAM","IMPL"}, {"RLA","IND,Y"},
    {"NOP","ZPG,X"},{"AND","ZPG,X"}, {"ROL","ZPG,X"},{"RLA","ZPG,X"},
    {"SEC","IMPL"}, {"AND","ABS,Y"}, {"NOP","IMPL"}, {"RLA","ABS,Y"},
    {"NOP","ABS,X"},{"AND","ABS,X"}, {"ROL","ABS,X"},{"RLA","ABS,X"},
    {"RTI","IMPL"}, {"EOR","IND,X"}, {"JAM","IMPL"}, {"SRE","IND,X"},
    {"NOP","ZPG"},  {"EOR","ZPG"},   {"LSR","ZPG"},  {"SRE","ZPG"},
    {"PHA","IMPL"}, {"EOR","IMM"},   {"LSR","ACC"},  {"ALR","IMM"},
    {"JMP","ABS"},  {"EOR","ABS"},   {"LSR","ABS"},  {"SRE","ABS"},
    {"BVC","REL"},  {"EOR","IND,Y"}, {"JAM","IMPL"}, {"SRE","IND,Y"},
    {"NOP","ZPG,X"},{"EOR","ZPG,X"}, {"LSR","ZPG,X"},{"SRE","ZPG,X"},
    {"CLI","IMPL"}, {"EOR","ABS,Y"}, {"NOP","IMPL"}, {"SRE","ABS,Y"},
    {"NOP","ABS,X"},{"EOR","ABS,X"}, {"LSR","ABS,X"},{"SRE","ABS,X"},
    {"RTS","IMPL"}, {"ADC","IND,X"}, {"JAM","IMPL"}, {"RRA","IND,X"},
    {"NOP","ZPG"},  {"ADC","ZPG"},   {"ROR","ZPG"},  {"RRA","ZPG"},
    {"PLA","IMPL"}, {"ADC","IMM"},   {"ROR","ACC"},  {"ARR","IMM"},
    {"JMP","IND"},  {"ADC","ABS"},   {"ROR","ABS"},  {"RRA","ABS"},
    {"BVS","REL"},  {"ADC","IND,Y"}, {"JAM","IMPL"}, {"RRA","IND,Y"},
    {"NOP","ZPG,X"},{"ADC","ZPG,X"}, {"ROR","ZPG,X"},{"RRA","ZPG,X"},
    {"SEI","IMPL"}, {"ADC","ABS,Y"}, {"NOP","IMPL"}, {"RRA","ABS,Y"},
    {"NOP","ABS,X"},{"ADC","ABS,X"}, {"ROR","ABS,X"},{"RRA","ABS,X"},
    {"NOP","IMM"},  {"STA","IND,X"}, {"NOP","IMM"},  {"SAX","IND,X"},
    {"STY","ZPG"},  {"STA","ZPG"},   {"STX","ZPG"},  {"SAX","ZPG"},
    {"DEY","IMPL"}, {"NOP","IMM"},   {"TXA","IMPL"}, {"ANE","IMM"},
    {"STY","ABS"},  {"STA","ABS"},   {"STX","ABS"},  {"SAX","ABS"},
    {"BCC","REL"},  {"STA","IND,Y"}, {"JAM","IMPL"}, {"SHA","IND,Y"},
    {"STY","ZPG,X"},{"STA","ZPG,X"}, {"STX","ZPG,Y"},{"SAX","ZPG,Y"},
    {"TYA","IMPL"}, {"STA","ABS,Y"}, {"TXS","IMPL"}, {"TAS","ABS,Y"},
    {"SHY","ABS,X"},{"STA","ABS,X"}, {"SHX","ABS,Y"},{"SHA","ABS,Y"},
    {"LDY","IMM"},  {"LDA","IND,X"}, {"LDX","IMM"},  {"LAX","IND,X"},
    {"LDY","ZPG"},  {"LDA","ZPG"},   {"LDX","ZPG"},  {"LAX","ZPG"},
    {"TAY","IMPL"}, {"LDA","IMM"},   {"TAX","IMPL"}, {"LXA","IMM"},
    {"LDY","ABS"},  {"LDA","ABS"},   {"LDX","ABS"},  {"LAX","ABS"},
    {"BCS","REL"},  {"LDA","IND,Y"}, {"JAM","IMPL"}, {"LAX","IND,Y"},
    {"LDY","ZPG,X"},{"LDA","ZPG,X"}, {"LDX","ZPG,Y"},{"LAX","ZPG,Y"},
    {"CLV","IMPL"}, {"LDA","ABS,Y"}, {"TSX","IMPL"}, {"LAS","ABS,Y"},
    {"LDY","ABS,X"},{"LDA","ABS,X"}, {"LDX","ABS,Y"},{"LAX","ABS,Y"},
    {"CPY","IMM"},  {"CMP","IND,X"}, {"NOP","IMM"},  {"DCP","IND,X"},
    {"CPY","ZPG"},  {"CMP","ZPG"},   {"DEC","ZPG"},  {"DCP","ZPG"},
    {"INY","IMPL"}, {"CMP","IMM"},   {"DEX","IMPL"}, {"SBX","IMM"},
    {"CPY","ABS"},  {"CMP","ABS"},   {"DEC","ABS"},  {"DCP","ABS"},
    {"BNE","REL"},  {"CMP","IND,Y"}, {"JAM","IMPL"}, {"DCP","IND,Y"},
    {"NOP","ZPG,X"},{"CMP","ZPG,X"}, {"DEC","ZPG,X"},{"DCP","ZPG,X"},
    {"CLD","IMPL"}, {"CMP","ABS,Y"}, {"NOP","IMPL"}, {"DCP","ABS,Y"},
    {"NOP","ABS,X"},{"CMP","ABS,X"}, {"DEC","ABS,X"},{"DCP","ABS,X"},
    {"CPX","IMM"},  {"SBC","IND,X"}, {"NOP","IMM"},  {"ISC","IND,X"},
    {"CPX","ZPG"},  {"SBC","ZPG"},   {"INC","ZPG"},  {"ISC","ZPG"},
    {"INX","IMPL"}, {"SBC","IMM"},   {"NOP","IMPL"}, {"SBC","IMM"},
    {"CPX","ABS"},  {"SBC","ABS"},   {"INC","ABS"},  {"ISC","ABS"},
    {"BEQ","REL"},  {"SBC","IND,Y"}, {"JAM","IMPL"}, {"ISC","IND,Y"},
    {"NOP","ZPG,X"},{"SBC","ZPG,X"}, {"INC","ZPG,X"},{"ISC","ZPG,X"},
    {"SED","IMPL"}, {"SBC","ABS,Y"}, {"NOP","IMPL"}, {"ISC","ABS,Y"},
    {"NOP","ABS,X"},{"SBC","ABS,X"}, {"INC","ABS,X"},{"ISC","ABS,X"}
};

boolean[] debugBooleans = new boolean[0];

//String[] logTable = new String[0];
